config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'



  # get '/posts', to: 'posts#index'
  # get '/posts/:id', to: 'posts#show'
  # get '/posts/new', to: 'posts#new'
  # post '/posts', to: 'post#create'
  # get '/posts/:id/edit', to: 'post#edit'
  # patch '/posts/:id', to: 'post#update'


  resources :posts, except: [:destroy] do
    member do
      post :vote #POST '/posts/:id/vote', to: 'post#vote'
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end


  resources :categories, only: [:show, :new, :create]


  resources :users, only: [:create, :show, :edit, :update]
  get '/register', to: 'users#new'


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create

    ### ALTERNATIVE ####
    # @post = Post.find(params[:id])
    # @comment = @post.comments.build(params.require(:comment).permit(:body))
    
    @post = Post.find_by(slug: params[:post_id])
    @comment = Comment.new(params.require(:comment).permit(:body))
    @comment.post = @post
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = "Your comment was added."
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end


  def vote
    @comment = Comment.find(params[:id])

    @vote = Vote.create(voteable: @comment, vote: params[:vote], creator: current_user)

    respond_to do |format|
      format.html {
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You can only vote on a comment once."
        end
        redirect_to :back
      }

      format.js {}
    end
  end

end

app/views/comments/_comment.html.erb
<% show_post ||= false %>

<div class="row">

  <!-- vote box -->
  <div class="well span0 text-center">
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'POST', remote: true do %>
        <i class="icon-arrow-up"></i>
      <% end %>
      <br/>
    <% end %>
      
    <span id='comment_<%=comment.id%>_votes'><%= comment.total_votes %> Vote(s)</span>

    <% if logged_in? %>
      <br/>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'POST', remote: true do %>
        <i class="icon-arrow-down"></i>
      <% end %>  
    <% end %>  
  </div>
  
  
  <!-- comment box -->
  <div class="well span8">
    <em>"<%= comment.body %>"</em>
    <% if show_post %>
      on <%= link_to comment.post.title, post_path(comment.post) %>
    <% end %>
    <br/>
    <span class="quiet">By:</span> 
    <%= link_to comment.creator.username, user_path(comment.creator) %>
    <% if comment.creator.admin? %>
      <span class="label label-warning">ADMIN</span>
    <% end %> 
    on <small><%= fix_date(comment.created_at) %></small>
  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $('#comment_<%=@comment.id%>_votes').html('<%=@comment.total_votes%> Vote(s)');
<% else %>
  alert('You can only vote on a comment once.')
<% end %>