config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'



  # get '/posts', to: 'posts#index'
  # get '/posts/:id', to: 'posts#show'
  # get '/posts/new', to: 'posts#new'
  # post '/posts', to: 'post#create'
  # get '/posts/:id/edit', to: 'post#edit'
  # patch '/posts/:id', to: 'post#update'


  resources :posts, except: [:destroy] do
    member do
      post :vote #POST '/posts/:id/vote', to: 'post#vote'
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end


  resources :categories, only: [:show, :new, :create]


  resources :users, only: [:create, :show, :edit, :update]
  get '/register', to: 'users#new'


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable
    sluggable_column :title

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories , through: :post_categories

  validates :title, presence: true, length: {minimum: 3}
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]


  def index 
    @posts = Post.all.sort_by{ |e| e.total_votes }.reverse

    respond_to do |format|
      format.html {}

      format.json { render json: @posts }
    end
  end


  def show
    @comment = Comment.new
  end


  def new
    @post = Post.new
  end


  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "Your post was saved."
      redirect_to posts_path
    else #validation error
      render 'new' #rendering allows us to display the errors
    end
  end


  def edit

  end


  def update
    if @post.update(post_params)
      flash[:notice] = "The post has been updated."
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end


  def vote
    @vote = Vote.create(voteable: @post, vote: params[:vote], creator: current_user)

    respond_to do |format|
      format.html {
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You can only vote on a post once."
        end
        redirect_to :back
      }

      format.js {}
    end
    
  end


  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end


  def set_post
    @post = Post.find_by(slug: params[:id])
  end


  def require_creator
    access_denied unless logged_in? && (current_user.admin? || current_user == @post.creator)
  end

end

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<div class="well">
  <%= form_for @post do |f| %>
    <div class="control-group"> 
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    
    <div class="control-group">  
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    
    <div class="control-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5 %>
    </div>
    
    <div class="control-group">
      <%= f.label "Categories" %>
      <% if logged_in? && current_user.admin? %>
        <p class="pull-right">[<%= link_to "New Category", new_category_path %>]</p>
      <% end %>  
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <%= cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
      <% end %> 
    </div> 
    
    <div class="control-group">
      <%= f.submit(@post.new_record? ? "Submit Post" : "Update Post", class: "btn btn-primary") %>
    </div>
  <% end %>


  <!-- HTML ONLY SELECT -->
  
  <!--<select name="post[category_ids][]" multiple="multiple">
      <option value='1'>Category 1</option>
      <option value='2'>Category 2</option>
    </select> -->


</div>

app/views/posts/_post.html.erb
<div class="row">
  <!-- Vote Box -->
  <div class="span0 well text-center">
    <% if logged_in? %>  
      <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
        <i class="icon-arrow-up"></i>
      <% end %>
      </br>
    <% end %>  

  <span id="post_<%=post.slug%>_votes"><%= post.total_votes %> Vote(s)</span>
  
    <% if logged_in? %>
      </br>
      <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% end %>  
  </div>
  


  <!--Post content box -->
  <div class="span8 well">
    <%= render post.categories %>

    <p class="pull-right">  
      <span class="icon-comment"></span>
      <small><%= "#{post.comments.size} comment(s)" %></small> 
    </p>
    
    <h4><%= link_to post.title, post_path(post) %></h4>

    <p>
      <span class="quiet">Posted by:</span> 
      <%= link_to post.creator.username, user_path(post.creator) %> 
      <% if post.creator.admin? %>
        <span class="label label-warning">ADMIN</span>
      <% end %>
      on <small><%= fix_date(post.created_at) %></small>
    </p>

    <p><%= link_to post.url, fix_url(post.url) %></p>

    <p><%= post.description %></p>
  </div>
</div>

app/views/posts/_welcome.html.erb
<h1>TEST</h1>

app/views/posts/edit.html.erb
<%= render '/shared/content_title', title: 'Edit Post' %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render '/shared/content_title', title: 'All Posts' %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>  

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a New Post' %>

<%= render 'form' %>








<!-- THESE ARE EXAMPLES OF DIFFERENT WAYS TO CREATE FORMS --> 

<!-- <h5>Pure HTML</h5>
<form action='/posts' method='POST'>
  Title: <input type='text'>
  <br/>
  <input type='submit'>
</form>

<br/>

<h5>Rails Form Helper</h5>
<%= form_tag '/posts' do %>
  <%= label_tag :title %>
  <%= text_field_tag :title %>
  <br/>
  <%= submit_tag "Create Post" %>
<% end %>

<br/>

<h5>Rails Model-Backed Form</h5>

<% if @post.errors.any? %>
  <div class="alert alert-error">
    <h5>Oops!</h5>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br/>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <br/>
  <%= f.submit "Submit Post" %>
<% end %> -->

app/views/posts/show.html.erb
<p class="pull-right">
  [<%= link_to "edit this post", edit_post_path(@post) %>]
</p>

<p>  
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<h4>
  <%= link_to @post.url, fix_url(@post.url) %>
</h4>
<p>
  <%= @post.description %>
</p>


<% if logged_in? %>
  <hr/>
  <%= form_for [@post, @comment] do |f| %>
    <%= render 'shared/errors', obj: @comment %>
    <div class='control-group'>
      <%= f.label :body, "Leave a comment" %> 
      <%= f.text_area :body, rows: 3, class: "span4" %>
    </div>  
    <%= f.submit "Create Comment", class: "btn btn-primary btn-small" %>
  <% end %>
<% end %>

<hr/>

<h5>Comments:</h5>

<% @post.comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment%>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $('#post_<%=@post.slug%>_votes').html('<%=@post.total_votes%> Vote(s)');
<% else %>
  alert('You can only vote on a post once.');
<% end %>