config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'



  # get '/posts', to: 'posts#index'
  # get '/posts/:id', to: 'posts#show'
  # get '/posts/new', to: 'posts#new'
  # post '/posts', to: 'post#create'
  # get '/posts/:id/edit', to: 'post#edit'
  # patch '/posts/:id', to: 'post#update'


  resources :posts, except: [:destroy] do
    member do
      post :vote #POST '/posts/:id/vote', to: 'post#vote'
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end


  resources :categories, only: [:show, :new, :create]


  resources :users, only: [:create, :show, :edit, :update]
  get '/register', to: 'users#new'


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable
    sluggable_column :name

  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create]
  before_action :require_admin, only: [:new, :create]

  def show
    @category = Category.find_by(slug: params[:id])
  end


  def new
    @category = Category.new
  end


  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category Created."
      redirect_to root_path
    else
      render :new
    end
  end


  private


  def category_params
    params.require(:category).permit(:name)
  end

end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: "Create a New Category" %>

<%= render 'shared/errors', obj: @category %> 

<div class="well">
  <%= form_for @category do |f| %>
    <div class="control-group">  
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: "Must be unique" %>
    </div>
    <%= f.submit "Create Category", class: "btn btn-success" %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% header = link_to('All Posts', posts_path) + " &raquo; #{@category.name}".html_safe  %>

<%= render "shared/content_title", title: header%>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>